#!/bin/bash

set -e

COLLECTOR_NAME="collector-junit"
COLLECTOR_VERSION="0.1"

echo -e "\033[33m     _ _   _       _ _      ____      _ _           _
    | | | | |_ __ (_| |_   / ___|___ | | | ___  ___| |_ ___  _ __
 _  | | | | | '_ \| | __| | |   / _ \| | |/ _ \/ __| __/ _ \| '__|
| |_| | |_| | | | | | |_  | |__| (_) | | |  __| (__| || (_) | |
 \___/ \___/|_| |_|_|\__|  \____\___/|_|_|\___|\___|\__\___/|_|

Buildkite Test Analytics: JUnit Collector
Version: $COLLECTOR_VERSION
\033[0m"

# Detect tty and error with usage message
if [ -t 0 ]; then
  echo "No JUnit stream found on STDIN"
  echo ""
  echo "Usage: cat junit.xml | TEST_ANALYTICS_TOKEN=xyz ./buildkite-collector-junit"
  exit 1
fi

# Based on the rules defined here:
# https://github.com/buildkite/rspec-buildkite-analytics/blob/main/lib/buildkite/collector/ci.rb

if [[ -n $BUILDKITE_BUILD_ID ]]; then
  echo "Detected Buildkite CI environment"

  COLLECTOR_CI="buildkite"
  COLLECTOR_KEY=$BUILDKITE_BUILD_ID
  COLLECTOR_NUMBER=$BUILDKITE_BUILD_NUMBER
  COLLECTOR_JOB_ID=$BUILDKITE_JOB_ID
  COLLECTOR_BRANCH=$BUILDKITE_BRANCH
  COLLECTOR_COMMIT_SHA=$BUILDKITE_COMMIT
  COLLECTOR_MESSAGE=$BUILDKITE_MESSAGE
  COLLECTOR_URL=$BUILDKITE_BUILD_URL
elif [[ -n $GITHUB_RUN_NUMBER ]]; then
  echo "Detected GitHub Actions CI environment"

  COLLECTOR_CI="github_actions"
  COLLECTOR_KEY="$GITHUB_ACTION-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT"
  COLLECTOR_NUMBER=$GITHUB_RUN_NUMBER
  COLLECTOR_BRANCH=$GITHUB_REF
  COLLECTOR_COMMIT_SHA=$GITHUB_SHA
  COLLECTOR_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
elif [[ -n $CIRCLE_BUILD_NUM ]]; then
  echo "Detected CircleCI environment"

  COLLECTOR_CI="circleci"
  COLLECTOR_KEY="$CIRCLE_WORKFLOW_ID-$CIRCLE_BUILD_NUM"
  COLLECTOR_NUMBER=$CIRCLE_BUILD_NUM
  COLLECTOR_BRANCH=$CIRCLE_BRANCH
  COLLECTOR_COMMIT_SHA=$CIRCLE_SHA1
  COLLECTOR_URL=$CIRCLE_BUILD_URL
elif [[ -n $CI ]]; then
  echo "Detected generic CI environment"

  COLLECTOR_CI="generic"
  COLLECTOR_KEY="$$"
else
  echo "No CI environment detected"

  COLLECTOR_KEY="$$"
fi

JUNIT_DATA_PATH="/tmp/bk-collector-junit-data-$$.xml"
cat ${1--} > $JUNIT_DATA_PATH

TEST_ANALYTICS_HTTP_URL="http://analytics-api.buildkite.localhost/v1/uploads"
TEST_ANALYTICS_HTTP_AUTH='Authorization: Token token="'$TEST_ANALYTICS_TOKEN'";'

echo ""
echo "Uploading results to Buildkite Test Analytics. One moment please..."
echo ""

if command -v curl >/dev/null; then
  set +e
  curl \
    --fail-with-body \
    --request POST \
    --url "$TEST_ANALYTICS_HTTP_URL" \
    --header "$TEST_ANALYTICS_HTTP_AUTH" \
    -F "format=junit" \
    -F "run_env[CI]=$COLLECTOR_CI" \
    -F "run_env[key]=$COLLECTOR_KEY" \
    -F "run_env[number]=$COLLECTOR_NUMBER" \
    -F "run_env[job_id]=$COLLECTOR_JOB_ID" \
    -F "run_env[branch]=$COLLECTOR_BRANCH" \
    -F "run_env[commit_sha]=$COLLECTOR_COMMIT_SHA" \
    -F "run_env[message]=$COLLECTOR_MESSAGE" \
    -F "run_env[url]=$COLLECTOR_URL" \
    -F "run_env[debug]=$BUILDKITE_ANALYTICS_DEBUG_ENABLED" \
    -F "run_env[collector]=$COLLECTOR_NAME" \
    -F "run_env[version]=$COLLECTOR_VERSION" \
    -F "data=@$JUNIT_DATA_PATH"
  UPLOAD_EXIT_STATUS=$?
  set -e
else
  echo "wget support hasn't been added for uploads yet"
  exit 1
fi

if [[ $UPLOAD_EXIT_STATUS -ne 0 ]]; then
  echo ""
  echo "❌ Something went wrong..."
  exit 1
else
  echo ""
  echo ""
  echo "✅ Uploaded!"
  exit 0
fi
